
# api_article:
#     resource: "@ApiBundle/Controller/ArticleController.php"
#     type:     annotation

api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   /api

admin:
    type:     rest
    resource: ApiBundle\Controller\DefaultController

articles:
    type:     rest
    resource: ApiBundle\Controller\ArticleController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    type: rest

facebook_login:
    path: /login/check-faceboof
